version: '3.1'

services:

  api:
    build: api
    environment:
      MONGO_URI: mongodb://mongo:27017/paranuara
    ports:
      - "5000:5000"

  mongo:
    image: mongo:4.2.7
    environment:
      MONGO_INITDB_DATABASE: paranuara
    volumes:
      - ./resources:/docker-entrypoint-initdb.d:ro
