version: '3.1'

services:

  api:
    build: api
    environment:
      MONGODB_DB:   paranuara
      MONGODB_HOST: mongo
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.7
    environment:
      MONGO_INITDB_DATABASE: paranuara
    volumes:
      - ./resources:/docker-entrypoint-initdb.d:ro
